include:
  - board: fhk_right
    #shield: dongle_screen
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: fhk_left
    shield: dongle_screen
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: fhk_studio_left
  - board: fhk_left
    shield: settings_reset
  - board: fhk_right
    shield: settings_reset
 
