include:
  - board: fhk_right
  - board: fhk_left
    shield: dongle_display
    snippet: studio-rpc-usb-uart
    artifact-name: fhk_studio_left
  - board: fhk_left
    shield: settings_reset
  - board: fhk_right
    shield: settings_reset
 
