include:
  - board: fhk_right
    #shield: nice_view_gem
  - board: fhk_left
    shield: nice_view_gem
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: fhk_studio_left
  - board: fhk_left
    shield: settings_reset
  - board: fhk_right
    shield: settings_reset
 
