include:
  - board: fhk_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: fhk_left
    shield: dongle_display
    snippet: studio-rpc-usb-uart
    artifact-name: fhk_studio_left
  - board: fhk_left
    shield: settings_reset
  - board: fhk_right
    shield: settings_reset
 
