include:
  - board: fhk_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: fhk_split_right
  - board: fhk_left
    shield: dongle_display
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: fhk_studio_left
  - board: nrfmicro/nrf52840
    shield: settings_reset
    artifact-name: fhk_settings_reset
