include:
  - board: fhk_right
    shield: nice-view-gem
    snippet: zmk-usb-logging
  - board: fhk_left
    shield: nice-view-gem
    snippet: studio-rpc-usb-uart zmk-usb-logging
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: fhk_studio_left
  - board: fhk_left
    shield: settings_reset
    snippet: zmk-usb-logging
 
