manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: Fushilaofang
      url-base: https://github.com/Fushilaofang  
  projects:
    - name: ZMK-FHK
      url: https://github.com/Fushilaofang/ZMK-FHK
      revision: master
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: nice-view-gem
      remote: Fushilaofang
      revision: LS013B7DH03 
  self:
    path: config