manifest:
  remotes:
    - name: petejohanson
      url-base: https://github.com/petejohanson
    - name: Fushilaofang
      url-base: https://github.com/Fushilaofang  
  projects:
    - name: ZMK-FHK
      url: https://github.com/Fushilaofang/ZMK-FHK
      revision: master
    - name: zmk
      remote: petejohanson
      revision: core/move-to-zephyr-4-1
      import: app/west.yml
    - name: zmk-dongle-display-bongocat
      remote: Fushilaofang
      revision: YDP154H008-V3
    - name: zmk-driver-azoteq-iqs5xx
      remote: Fushilaofang
      revision: main
    - name: ydp154h008-v3-zmk-module
      remote: Fushilaofang
      revision: main      
  self:
    path: config
