manifest:
  remotes:
    - name: petejohanson
      url-base: https://github.com/petejohanson
    - name: Fu
      url-base: https://github.com/Fu 
  projects:
    - name: ZMK-FHK
      url: https://github.com/Fu/ZMK-FHK
      revision: master
    - name: zmk
      remote: petejohanson
      revision: core/move-to-zephyr-4-1
      import: app/west.yml
  self:
    path: config
