manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: Fushilaofang
      url-base: https://github.com/Fushilaofang  
  projects:
    - name: ZMK-FHK
      url: https://github.com/Fushilaofang/ZMK-FHK
      revision: master
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-dongle-display-bongocat
      remote: Fushilaofang
      revision: main
    - name: zmk-driver-azoteq-iqs5xx
      remote: Fushilaofang
      revision: main
  self:
    path: config
